### ISSUE TITLE
세미콜론 좀 넣어주세요

### ISSUE THREAD

**Issue by Krdaha** [Krchip/gyeongsonbot#2]
<h1>세미콜론 좀 넣어주세요</h1>

css 할 때 세미콜론 필수인데, 세미콜론 없으니까 개인적으로 좀 불편하네요.

**Comment by Krchip** [comment]
다음 패치에 적용될 예정입니다, 감사합니다.

**Comment by Bixbyi** [comment]
옛날에 '\n'+'' 하신 분이
